import { MenuItem } from '@/store/cafe-store';

export const menuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Caramel Macchiato',
    description: 'Velvety steamed milk marked with espresso and topped with buttery caramel drizzle. A perfect balance of sweet and bold.',
    price: 549,
    image: '/images/cafe/product-1.png',
    category: 'hot-coffee',
    rating: 4.8,
    reviews: 2847,
    isBestseller: true,
    isLimited: false,
    isNew: false,
    popularity: 98,
    tags: ['bestseller', 'popular'],
  },
  {
    id: '2',
    name: 'Mocha Latte',
    description: 'Rich espresso blended with premium Belgian chocolate and steamed milk, crowned with whipped cream and cocoa dust.',
    price: 499,
    image: '/images/cafe/product-2.png',
    category: 'hot-coffee',
    rating: 4.7,
    reviews: 2156,
    isBestseller: true,
    isLimited: false,
    isNew: false,
    popularity: 95,
    tags: ['bestseller', 'chocolate'],
  },
  {
    id: '3',
    name: 'Iced Matcha Latte',
    description: 'Ceremonial-grade Japanese matcha whisked with oat milk over ice. Earthy, vibrant, and refreshingly smooth.',
    price: 579,
    image: '/images/cafe/product-3.png',
    category: 'cold-drinks',
    rating: 4.9,
    reviews: 1823,
    isBestseller: false,
    isLimited: false,
    isNew: true,
    popularity: 92,
    tags: ['new', 'healthy'],
  },
  {
    id: '4',
    name: 'Espresso Doppio',
    description: 'A double shot of our signature dark roast, sourced from Ethiopian highlands. Intense, aromatic, and perfectly extracted.',
    price: 379,
    image: '/images/cafe/product-4.png',
    category: 'hot-coffee',
    rating: 4.6,
    reviews: 3241,
    isBestseller: true,
    isLimited: false,
    isNew: false,
    popularity: 97,
    tags: ['classic', 'strong'],
  },
  {
    id: '5',
    name: 'Affogato',
    description: 'Two scoops of house-made vanilla gelato drowned in a freshly pulled shot of espresso. A dessert and coffee in one.',
    price: 649,
    image: '/images/cafe/product-5.png',
    category: 'specialties',
    rating: 4.9,
    reviews: 1456,
    isBestseller: false,
    isLimited: true,
    isNew: false,
    popularity: 88,
    tags: ['limited', 'dessert'],
  },
  {
    id: '6',
    name: 'Cold Brew Reserve',
    description: 'Slow-steeped for 24 hours using single-origin Colombian beans. Smooth, naturally sweet, with chocolate undertones.',
    price: 449,
    image: '/images/cafe/product-6.png',
    category: 'cold-drinks',
    rating: 4.7,
    reviews: 2678,
    isBestseller: false,
    isLimited: false,
    isNew: false,
    popularity: 94,
    tags: ['refreshing', 'smooth'],
  },
  {
    id: '7',
    name: 'Artisan Croissant Trio',
    description: 'Three handcrafted croissants: classic butter, dark chocolate, and almond. Flaky, golden, and baked fresh every morning.',
    price: 749,
    image: '/images/cafe/product-7.png',
    category: 'pastries',
    rating: 4.8,
    reviews: 1987,
    isBestseller: true,
    isLimited: false,
    isNew: false,
    popularity: 93,
    tags: ['bestseller', 'breakfast'],
  },
  {
    id: '8',
    name: 'Berry Cheesecake',
    description: 'New York-style cheesecake topped with fresh seasonal berries and a delicate berry coulis. Creamy, tangy, divine.',
    price: 629,
    image: '/images/cafe/product-8.png',
    category: 'desserts',
    rating: 4.9,
    reviews: 1567,
    isBestseller: false,
    isLimited: true,
    isNew: false,
    popularity: 89,
    tags: ['limited', 'dessert'],
  },
  {
    id: '9',
    name: 'Avocado Toast',
    description: 'Smashed avocado on artisan sourdough, topped with a poached egg, microgreens, and edible flowers. Brunch perfection.',
    price: 799,
    image: '/images/cafe/product-9.png',
    category: 'food',
    rating: 4.7,
    reviews: 2234,
    isBestseller: true,
    isLimited: false,
    isNew: false,
    popularity: 91,
    tags: ['bestseller', 'brunch'],
  },
  {
    id: '10',
    name: 'Chocolate Lava Cake',
    description: 'Warm dark chocolate cake with a molten center, served with vanilla bean ice cream and gold dust. Pure indulgence.',
    price: 899,
    image: '/images/cafe/product-10.png',
    category: 'desserts',
    rating: 5.0,
    reviews: 987,
    isBestseller: false,
    isLimited: true,
    isNew: true,
    popularity: 96,
    tags: ['new', 'limited', 'premium'],
  },
];

export const categories = [
  { id: 'all', name: 'All', icon: '/icons/All.png' },
  { id: 'hot-coffee', name: 'Hot Coffee', icon: '/icons/hotcoffee.png' },
  { id: 'cold-drinks', name: 'Cold Drinks', icon: '/icons/colddrinks.png' },
  { id: 'specialties', name: 'Specialties', icon: '/icons/Specialties.png' },
  { id: 'pastries', name: 'Pastries', icon: '/icons/Pastries.png' },
  { id: 'desserts', name: 'Desserts', icon: '/icons/dessert.png' },
  { id: 'food', name: 'Food', icon: '/icons/Food.png' },
];

export const popularSearches = ['Caramel Macchiato', 'Espresso', 'Matcha Latte', 'Cold Brew', 'Croissant'];
export const trendingItems = ['3', '10', '5', '1'];
export const chefPicks = ['2', '8', '9', '10'];
export const seasonalSpecials = ['5', '3', '8', '10'];

export const reviews = [
  { id: '1', name: 'Sarah M.', avatar: 'SM', rating: 5, text: 'Absolutely divine! The Caramel Macchiato here is the best I have ever tasted. The atmosphere is so warm and inviting, it feels like a second home. The staff remembers your name and your order - that personal touch makes all the difference.', date: '2 days ago', item: 'Caramel Macchiato', helpful: 42 },
  { id: '2', name: 'James K.', avatar: 'JK', rating: 5, text: 'The Chocolate Lava Cake is a masterpiece. When you break through that outer layer and the molten center flows out... pure heaven. Paired with their espresso, it is an experience, not just a dessert. Will be back every weekend.', date: '1 week ago', item: 'Chocolate Lava Cake', helpful: 38 },
  { id: '3', name: 'Emily R.', avatar: 'ER', rating: 4, text: 'Love the Iced Matcha Latte! The matcha quality is outstanding - you can tell they use ceremonial grade. The oat milk pairs perfectly. Only wish they had more seating during peak hours, but the quality makes up for it.', date: '3 days ago', item: 'Iced Matcha Latte', helpful: 29 },
  { id: '4', name: 'Michael T.', avatar: 'MT', rating: 5, text: 'This place redefines what a coffee shop can be. The Affogato is incredible, and the ambiance is unmatched. Soft lighting, beautiful decor, and the aroma of freshly roasted beans greeting you at the door. A true gem in the city.', date: '5 days ago', item: 'Affogato', helpful: 56 },
  { id: '5', name: 'Lisa W.', avatar: 'LW', rating: 5, text: 'The Avocado Toast is worth every penny. Perfectly poached eggs, beautiful presentation, and the sourdough is baked in-house. This is not just breakfast - it is a culinary experience. The coffee is equally exceptional.', date: '1 week ago', item: 'Avocado Toast', helpful: 33 },
  { id: '6', name: 'David C.', avatar: 'DC', rating: 4, text: 'Cold Brew Reserve is my go-to every morning. The 24-hour steeping process creates such a smooth, rich flavor without any bitterness. I have tried cold brews all over the city and nothing compares to what they do here.', date: '2 weeks ago', item: 'Cold Brew Reserve', helpful: 27 },
];

export const timeSlots = [
  '9:00 AM', '9:30 AM', '10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM',
  '12:00 PM', '12:30 PM', '1:00 PM', '1:30 PM', '2:00 PM', '2:30 PM',
  '3:00 PM', '3:30 PM', '4:00 PM', '4:30 PM', '5:00 PM', '5:30 PM',
  '6:00 PM', '6:30 PM', '7:00 PM', '7:30 PM', '8:00 PM', '8:30 PM', '9:00 PM',
];

export const seatingOptions = [
  { id: 'indoor-cozy', name: 'Indoor Cozy Corner', description: 'Soft armchairs near the fireplace', icon: '🛋️' },
  { id: 'indoor-window', name: 'Window Seat', description: 'Natural light with street views', icon: '🪟' },
  { id: 'outdoor-patio', name: 'Outdoor Patio', description: 'Al fresco dining with garden views', icon: '🌿' },
  { id: 'bar', name: 'Coffee Bar', description: 'Watch the barista at work', icon: '☕' },
  { id: 'private', name: 'Private Nook', description: 'Secluded area for intimate gatherings', icon: '🔒' },
];
